### PR TITLE
Sanity minimal starter example

### PR DESCRIPTION
**Pull request by jaydanurwin**
## What I did

1. Brought over the code for the Sanity Minimal Starter into the `examples` folder
2. Created README for the starter

### CODE REVIEW

**Comment by jaydanurwin** [comment]
@daKmoR I think it's ready to be added as an official starter! I'm not sure what needs to be done to add it the CLI though. Once it's on the CLI we can update the README with the proper command.

**Comment by jaydanurwin** [comment]
Thanks for catching the branch for the merge @daKmoR. Any feedback on the Sanity starter's code or am I good to merge?

**Comment by daKmoR** [comment]
I will run through it tonight 👍

**Comment by daKmoR** [comment]
unfortunately, my internet was flaky today... tried to install the backend multiple times but npm always failed at some point 😭

will try tomorrow 🤞

**Comment by jaydanurwin** [comment]
> unfortunately, my internet was flaky today... tried to install the backend multiple times but npm always failed at some point 😭
> 
> will try tomorrow 🤞

No worries! I've personally had better luck using Sanity's CLI and running `sanity install`. That might work better for you? I think I put all of that in the README too.

**Comment by jaydanurwin** [comment]
@daKmoR I just went through the updates and made a couple small tweaks to the README. I think the updated README makes sense for first time Sanity users. Should be ready to go! 👍🏼

**Pull request merged**
