### PR TITLE
fix: make markdown css not conflict with lion components

### PR DESCRIPTION
**Pull request by tlouisse**
Prevent styles from applying to lion components that are rendered in light dom

### CODE REVIEW

**Comment by bennypowers** [comment]
would you mind updating the mdjs dependency?

**Comment by tlouisse** [comment]
> would you mind updating the mdjs dependency?

Done :)

**Review by bennypowers — APPROVED** [review]
LGTM. @daKmoR ?

**Comment by daKmoR** [comment]
thx 👍

**Pull request merged**
