### PR TITLE
fix: #277 adding missing dependency to slash in package.json

### PR DESCRIPTION
**Pull request by movrack**
## What I did

1. adding missing dependency to slash @ ^4.0.0

### CODE REVIEW

**Comment by bennypowers** [comment]
what does this solve?

**Comment by gluck** [comment]
> what does this solve?

Reproduction path on an empty project:

```
$ npm init
$ npm install --save @mdjs/core
$ node
Welcome to Node.js v14.17.6.
Type ".help" for more information.
> require('@mdjs/core')
Uncaught Error: Cannot find module 'slash'
Require stack:
- /tmp/repro/node_modules/@mdjs/core/src/mdjsSetupCode.js
- /tmp/repro/node_modules/@mdjs/core/index.js
...
```

**Comment by bennypowers** [comment]
I see
This will require a changeset, please add one 🙏

**Comment by gluck** [comment]
(Note that current PR also fails reproduction path because slash moved to ESM-only in v4, hence `require('slash')` will fail)
Need to pin to v3 instead as elsewhere in this repo, and update yarn.lock as well.

**Pull request closed without merging**
